### ISSUE TITLE
Request: Instance Domain vs. Instance Hostname

### ISSUE THREAD

**Issue by alexte** [TheKinrar/mastodon-instances#38]
If an instance hosts users of @domain but runs on host.domain, registering @domain does not work.
I could only register host.domain.

I think it would be nice to store both, that users can search for a domain and then be directed to the instances hostname.

**Comment by ayush-sharma** [comment]
Agreed. Currently I can't provide a link to the instances from the API since the instance host and URL are not returned in the API response. Generating links to instances requires parsing the instance name, and that is not always correct, since instance names also begin with "@" symbol.

**Comment by TheKinrar** [comment]
@alexte Can you please send me the link to an instance that does such thing so that I can look into this?

I think I can add a special field to show the address people will get, but the web domain of the instance will most probably remain what's shown on the listing.

@ayush-sharma I don't understand what you mean. Instance names do not begin with an @ symbol. You can generate link with something like "https://*instance.name*", with *instance* being an object returned by the [API](https://instances.social/api/doc).

**Comment by alexte** [comment]
@TheKinrar Thank you for the response. 

I had this case personally. I run mail.at and was running a mastodon instance for users@mail.at on mastodon.mail.at. Unfortunately I shut down my instance and ended my mastodon experiments, because it did not work out for small sites.

Perhaps there is no sample of this configuration because it's currently not really supported.

**Comment by TheKinrar** [comment]
Okay, then, I'll close this unless someone else is concerned. Thanks for your answer.
