### ISSUE TITLE
cannot sign up in admin space

### ISSUE THREAD

**Issue by steckerhalter** [TheKinrar/mastodon-instances#63]
so I'm trying to sing up [smusi.ch](https://smusi.ch) but I get an error and it says:
> Something went wrong. Check the instance name is valid and a contact email is set in the site settings of Mastodon. Contact @TheKinrar@mastodon.xyz if you need help.

well, I did that but didn't get a reply. and what's up with the "contact email"? I can't find this anywhere. there's "business e-mail" and I have filled that in

**Comment by TheKinrar** [comment]
Contact email and business email are the same.
Emails **are** sent, if they don't show in your inbox then the issue is with your server.

Anyway. I answer DMs I receive about these issues, I just might need some hours or some days sometimes. If you want a faster answer and, most importantly, want to be absolutely sure I'll answer, use email. contact@thekinrar.fr

**Comment by steckerhalter** [comment]
I didn't get any emails on my server which is a postfix mail server. there's nothing in the mail server logs that indicates an attempt to deliver an email.

**Comment by steckerhalter** [comment]
@camarigor so is it working for you now?
